### ISSUE TITLE
Encrypt passwords on frontend and backend

### ISSUE THREAD

**Issue by csirianni** [csirianni/private-data-lookup#21]
# Description

Convert the provided user password to a hashed point on the elliptical curve and apply scalar multiplication with secret key `a`. Convert the generated breached passwords to a hashed point on the elliptical curve and apply scalar multiplication with secret key `b`. Unit test both implementations.

# Acceptance Criteria

- Both encryption schemes are tested.
- The `cryptography` interface on the backend should return byte arrays, not strings.

**Comment by stellaljung** [comment]
[Here](https://github.com/KinanBab/CSCI2390-cryptography-primer) is Kinan's example from class.
